# Álgebra Matricial

## Vetores e escalares

### Operações com vetores

In [1]:
import numpy as np

a = np.array([4,5,6])
b = np.array([1,2,3])

Operações com vetores.                                            

In [2]:
# Soma
a + b

array([5, 7, 9])

In [3]:
# Subtração
a - b

array([3, 3, 3])

In [4]:
# Multiplicação por escalar
alpha = 10
alpha*a

array([40, 50, 60])

In [5]:
# Produto interno
np.dot(a,b)

32

In [6]:
# Produto interno
a @ b

32

Diferentemente do comportamento da linguagem R com relação à lei da reciclagem, em Python a operação entre vetores de tamanhos diferentes não é permitida.

In [7]:
a = np.array([4,5,6,5,6,7])
b = np.array([1,2,3])

a + b

ValueError: operands could not be broadcast together with shapes (6,) (3,) 

O símbolo usual de multiplicação * não realiza a multiplicação vetorial, mas sim uma multiplicação elemento por elemento, também chamada de produto de Hadamard.

In [8]:
a = np.array([4,5,6])
b = np.array([1,2,3])

# Multiplicação elemento a elemento (Hadamard)
a * b

# Multiplicação elemento a elemento (Hadamard)
np.multiply(a, b)

array([ 4, 10, 18])

Usando as operações com vetores podemos facilmente calcular o co-seno do ângulo $\theta$ entre dois vetores compatíveis.

In [9]:
cos_theta = np.dot(a,b)/(np.sqrt(np.dot(a,a))*np.sqrt(np.dot(b,b)))
cos_theta

0.9746318461970762

## Matrizes

Podemos definir uma matriz em Python de forma direta ou por meio do comando <code>reshape()</code>, da biblioteca Numpy, que permite rearranjar um vetor em uma matriz.

Inicialização de uma matriz.

In [10]:
# Rearranjando um vetor
a = np.array([1,2,3,4,5,6])
A = a.reshape(3,2)
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
# Rearranjando um vetor
a = np.array([1,2,3,4,5,6])
A = np.reshape(a, (3,2))
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
# Declaração direta:
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

Diferentemente do R, em Python a matriz é preenchida por linha por padrão.

É possível também preencher a matriz por coluna, caso seja de interesse. Neste caso usamos o argumento <code>order="F"</code>.

In [13]:
A = np.reshape(a, (3,2), order="F")
A

array([[1, 4],
       [2, 5],
       [3, 6]])

A transposição de uma matriz ou vetor é realizada pela função <code>transpose()</code> da biblioteca Numpy.

Transposta de uma matriz.

In [14]:
a = np.array([1,2,3,4,5,6])
A = a.reshape(3,2)

A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [15]:
np.transpose(A)

array([[1, 3, 5],
       [2, 4, 6]])

### Operações com matrizes

Multiplicação de escalar por matriz.

In [16]:
A = np.reshape([1,2,3,4,5,6], (3,2), order="F")
alpha = 10
alpha*A

array([[10, 40],
       [20, 50],
       [30, 60]])

Soma de matrizes.

In [17]:
A = np.reshape([1,2,3,4,5,6], (3,2), order="F")
B = np.reshape([10,20,30,40,50,60], (3,2), order="F")
C = A + B
C

array([[11, 44],
       [22, 55],
       [33, 66]])

Multiplicação de matrizes.

In [18]:
A = np.reshape([2,8,6,-1,3,7], (3,2), order="F")
B = np.reshape([4,-5,9,2,1,4,-3,6], (2,4), order="F")
C = A @ B
C

array([[ 13,  16,  -2, -12],
       [ 17,  78,  20,  -6],
       [-11,  68,  34,  24]])

In [19]:
C = np.matmul(A,B)
C

array([[ 13,  16,  -2, -12],
       [ 17,  78,  20,  -6],
       [-11,  68,  34,  24]])

Multiplicação de matrizes não compatíveis.

In [20]:
B @ A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

Ilustração da diferença entre escalar e matriz $1 \times 1$.

In [21]:
alpha = 10
a = np.reshape([10], (1,1))
b = np.reshape([1,2,3,4], (1,4), order="F")
a.shape # Dimensão de A

(1, 1)

In [22]:
b.shape # Dimensão de B

(1, 4)

In [23]:
a @ b # Compatível

array([[10, 20, 30, 40]])

In [24]:
b @ a # Incompatível

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 4)

In [25]:
b.T @ a # Compatível

array([[10],
       [20],
       [30],
       [40]])

In [26]:
alpha*b # Escalar com matriz

array([[10, 20, 30, 40]])

In [27]:
b*alpha # Escalar com matriz

array([[10, 20, 30, 40]])

Produto de Hadamard.

In [28]:
A = np.reshape([1,2,3,4], (2,2), order="F")
B = np.reshape([10,20,30,40], (2,2), order="F")
A*B

array([[ 10,  90],
       [ 40, 160]])

### Matrizes de formas especiais

### Rank e inversa de uma matriz

Inversa de uma matriz.

In [29]:
A = np.reshape([4,2,7,6], (2,2), order="F")
A_inv = np.linalg.inv(A)
A @ A_inv # Conferindo: deve resultar na matriz identidade

array([[ 1.00000000e+00, -1.11022302e-16],
       [ 1.11022302e-16,  1.00000000e+00]])

Neste caso o vetor $\mathbf{a}^{-} = (1, 0, 0, 0)$ é a inversa generalizada de \mathbf{a}. Para verificar basta fazer a multiplicação matricial.

In [30]:
a = np.reshape([1,2,3,4], (4,1), order="F")
a_invg = np.reshape([1,0,0,0], (1,4), order="F")
a @ a_invg @ a

array([[1],
       [2],
       [3],
       [4]])

Inversa generalizada de Moore-Penrose.

In [31]:
# Matriz singular (a terceira coluna é a soma da primeira com a segunda)
A = np.reshape([2, 1, 3, 2, 0, 2, 3, 1, 4], (3,3), order="F")

A_ginv = np.linalg.pinv(A)

# Conferindo
A @ A_ginv @ A

array([[2.00000000e+00, 2.00000000e+00, 3.00000000e+00],
       [1.00000000e+00, 6.66133815e-16, 1.00000000e+00],
       [3.00000000e+00, 2.00000000e+00, 4.00000000e+00]])

### Matrizes positivas definidas

### Determinante e traço de uma matriz

Determinante de uma matriz.

In [32]:
A = np.reshape([3,-2,-2,4], (2,2), order="F")
np.linalg.det(A)

8.000000000000002

Diferentemente do R, a função <code>det()</code> da biblioteca NumPy não oferece a opção do determinante na escala logarítmica.

Traço de uma matriz.

In [33]:
A = np.reshape([3,-2,-2,4], (2,2), order="F")
sum(np.diag(A))

7

### Cálculo vetorial e matricial

### Regressão linear múltipla

Para exemplificar a implementação do modelo de regressão linear múltipla, vamos usar um conjunto de dados muito famoso sobre o preço de imóveis na cidade de Boston.

In [35]:
import os, ssl
if (not os.environ.get('PYTHONHTTPSVERIFY', '') and
getattr(ssl, '_create_unverified_context', None)):
    ssl._create_default_https_context = ssl._create_unverified_context

In [36]:
import pandas as pd

url = "https://raw.githubusercontent.com/juniorssz/datasets/main/general/boston.csv"
df = pd.read_csv(url)
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

O primeiro passo para implementar o modelo de regressão linear múltipla para este problema é montar a matriz $\mathbf{X}$, também chamada de matriz de delineamento. Ela vai conter os valores de todas as covariáveis de interesse.

In [37]:
X = df[['crim', 'zn', 'indus', 'chas', 'nox']] # Seleciona as covariáveis
X.insert(0, "(Intercept)", [1]*X.shape[0]) # Cria a coluna do intercepto
X.head()

(Intercept)     crim    zn  indus  chas    nox
0            1  0.00632  18.0   2.31     0  0.538
1            1  0.02731   0.0   7.07     0  0.469
2            1  0.02729   0.0   7.07     0  0.469
3            1  0.03237   0.0   2.18     0  0.458
4            1  0.06905   0.0   2.18     0  0.458

O vetor $y$ neste caso é a coluna medv.

In [38]:
y = df.medv

Tal diferença ficará clara quando discutirmos algoritmos para a solução de sistemas de equações lineares e obtenção da matriz inversa.

In [39]:
# Forma ingênua
coefs = np.linalg.inv(X.T @ X) @ X.T @ y
coefs = pd.DataFrame(coefs) # 
coefs.index = X.columns 
coefs

0
(Intercept)  29.489941
crim         -0.218519
zn            0.055110
indus        -0.383481
chas          7.026223
nox          -5.424659