# Álgebra Matricial

## Vetores e escalares

### Operações com vetores

In [1]:
import numpy as np

a = np.array([4,5,6])
b = np.array([1,2,3])

Operações com vetores.                                            

In [2]:
# Soma
a + b

array([5, 7, 9])

In [3]:
# Subtração
a - b

array([3, 3, 3])

In [4]:
# Multiplicação por escalar
alpha = 10
alpha*a

array([40, 50, 60])

In [5]:
# Produto interno
np.dot(a,b)

32

In [6]:
# Produto interno
a @ b

32

Diferentemente do comportamento da linguagem R com relação à lei da reciclagem, em Python a operação entre vetores de tamanhos diferentes não é permitida.

In [7]:
a = np.array([4,5,6,5,6,7])
b = np.array([1,2,3])

a + b

ValueError: operands could not be broadcast together with shapes (6,) (3,) 

O símbolo usual de multiplicação * não realiza a multiplicação vetorial, mas sim uma multiplicação elemento por elemento, também chamada de produto de Hadamard.

In [ ]:
a = np.array([4,5,6])
b = np.array([1,2,3])

# Multiplicação elemento a elemento (Hadamard)
a * b

# Multiplicação elemento a elemento (Hadamard)
np.multiply(a, b)

Usando as operações com vetores podemos facilmente calcular o co-seno do ângulo $\theta$ entre dois vetores compatíveis.

In [ ]:
cos_theta = np.dot(a,b)/(np.sqrt(np.dot(a,a))*np.sqrt(np.dot(b,b)))
cos_theta