# Álgebra Matricial

## Vetores e escalares

### Operações com vetores

In [1]:
import numpy as np

a = np.array([4,5,6])
b = np.array([1,2,3])

Operações com vetores.                                            

In [2]:
# Soma
a + b

array([5, 7, 9])

In [3]:
# Subtração
a - b

array([3, 3, 3])

In [4]:
# Multiplicação por escalar
alpha = 10
alpha*a

array([40, 50, 60])

In [5]:
# Produto interno
np.dot(a,b)

32

In [6]:
# Produto interno
a @ b

32

Diferentemente do comportamento da linguagem R com relação à lei da reciclagem, em Python a operação entre vetores de tamanhos diferentes não é permitida.

In [7]:
a = np.array([4,5,6,5,6,7])
b = np.array([1,2,3])

a + b

ValueError: operands could not be broadcast together with shapes (6,) (3,) 

O símbolo usual de multiplicação * não realiza a multiplicação vetorial, mas sim uma multiplicação elemento por elemento, também chamada de produto de Hadamard.

In [8]:
a = np.array([4,5,6])
b = np.array([1,2,3])

# Multiplicação elemento a elemento (Hadamard)
a * b

# Multiplicação elemento a elemento (Hadamard)
np.multiply(a, b)

array([ 4, 10, 18])

Usando as operações com vetores podemos facilmente calcular o co-seno do ângulo $\theta$ entre dois vetores compatíveis.

In [9]:
cos_theta = np.dot(a,b)/(np.sqrt(np.dot(a,a))*np.sqrt(np.dot(b,b)))
cos_theta

0.9746318461970762

## Matrizes

Podemos definir uma matriz em Python de forma direta ou por meio do comando <code>reshape()</code>, da biblioteca Numpy, que permite rearranjar um vetor em uma matriz.

Inicialização de uma matriz.

In [10]:
# Rearranjando um vetor
a = np.array([1,2,3,4,5,6])
A = a.reshape(3,2)
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
# Rearranjando um vetor
a = np.array([1,2,3,4,5,6])
A = np.reshape(a, (3,2))
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
# Declaração direta:
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

Diferentemente do R, em Python a matriz é preenchida por linha por padrão.

É possível também preencher a matriz por coluna, caso seja de interesse. Neste caso usamos o argumento <code>order="F"</code>.

In [13]:
A = np.reshape(a, (3,2), order="F")
A

array([[1, 4],
       [2, 5],
       [3, 6]])

A transposição de uma matriz ou vetor é realizada pela função <code>transpose()</code> da biblioteca Numpy.

Transposta de uma matriz.

In [14]:
a = np.array([1,2,3,4,5,6])
A = a.reshape(3,2)

A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [15]:
np.transpose(A)

array([[1, 3, 5],
       [2, 4, 6]])

### Operações com matrizes

Multiplicação de escalar por matriz.

In [16]:
A = np.reshape([1,2,3,4,5,6], (3,2), order="F")
alpha = 10
alpha*A

array([[10, 40],
       [20, 50],
       [30, 60]])

Soma de matrizes.

In [17]:
A = np.reshape([1,2,3,4,5,6], (3,2), order="F")
B = np.reshape([10,20,30,40,50,60], (3,2), order="F")
C = A + B
C

array([[11, 44],
       [22, 55],
       [33, 66]])

Multiplicação de matrizes.

In [18]:
A = np.reshape([2,8,6,-1,3,7], (3,2), order="F")
B = np.reshape([4,-5,9,2,1,4,-3,6], (2,4), order="F")
C = A @ B
C

array([[ 13,  16,  -2, -12],
       [ 17,  78,  20,  -6],
       [-11,  68,  34,  24]])

In [19]:
C = np.matmul(A,B)
C

array([[ 13,  16,  -2, -12],
       [ 17,  78,  20,  -6],
       [-11,  68,  34,  24]])

Multiplicação de matrizes não compatíveis.

In [20]:
B @ A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

Ilustração da diferença entre escalar e matriz $1 \times 1$.

In [21]:
alpha = 10
a = np.reshape([10], (1,1))
b = np.reshape([1,2,3,4], (1,4), order="F")
a.shape # Dimensão de A

(1, 1)

In [22]:
b.shape # Dimensão de B

(1, 4)

In [23]:
a @ b # Compatível

array([[10, 20, 30, 40]])

In [24]:
b @ a # Incompatível

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 4)

In [25]:
b.T @ a # Compatível

array([[10],
       [20],
       [30],
       [40]])

In [26]:
alpha*b # Escalar com matriz

array([[10, 20, 30, 40]])

In [27]:
b*alpha # Escalar com matriz

array([[10, 20, 30, 40]])

Produto de Hadamard.

In [28]:
A = np.reshape([1,2,3,4], (2,2), order="F")
B = np.reshape([10,20,30,40], (2,2), order="F")
A*B

array([[ 10,  90],
       [ 40, 160]])